name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '(deps') }}

    steps:
      - uses: actions/checkout@v2
      - uses: hmarr/debug-action@v2

      - name: Package CLI Application for Windows
        uses: yshalsager/pyinstaller-action-windows@main
        with:
          path: .
          spec: wit_transcriber.spec
          requirements: requirements.txt

      - name: Package GUI Application for Windows
        uses: yshalsager/pyinstaller-action-windows@main
        with:
          path: .
          spec: wit_transcriber_gui.spec
          requirements: requirements.txt

      - uses: actions/upload-artifact@v2
        if: github.actor != 'dependabot[bot]'
        with:
          name: wit_transcriber.exe
          path: dist/windows

      - uses: actions/upload-artifact@v2
        if: github.actor != 'dependabot[bot]'
        with:
          name: wit_transcriber_gui.exe
          path: dist/windows

      - name: Package CLI Application for Linux
        uses: yshalsager/pyinstaller-action-linux@main
        with:
          path: .
          spec: wit_transcriber.spec
          requirements: requirements.txt

      - name: Package GUI Application for Windows
        uses: yshalsager/pyinstaller-action-linux@main
        with:
          path: .
          spec: wit_transcriber_gui.spec
          requirements: requirements.txt

      - uses: actions/upload-artifact@v2
        if: github.actor != 'dependabot[bot]'
        with:
          name: wit_transcriber
          path: dist/linux

      - uses: actions/upload-artifact@v2
        if: github.actor != 'dependabot[bot]'
        with:
          name: wit_transcriber_gui
          path: dist/linux

      - name: Set release name to tag name or datetime
        id: release
        run: |
          echo ${{ github.ref }}
          ref='refs/tags/v'
          if [[ ${{ github.ref }} == *${ref}* ]]; then
            echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
          else
            echo ::set-output name=version::$(date +'%Y%m%d-%H%M%S')
          fi

      - name: Release
        if: github.actor != 'dependabot[bot]' && github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release.outputs.version }}
          name: ${{ steps.release.outputs.version }}
          files: |
            dist/windows/wit_transcriber.exe
            dist/linux/wit_transcriber
            dist/windows/wit_transcriber_gui.exe
            dist/linux/wit_transcriber_gui
